final List<String> alexandriaRegions = [
  "All",
  "Miami",
  "Mandara",
  "Asafra",
  "El Syouf Shma3a",
  "Tram Syouf",
  "El Awayed",
  "Al-Mansheya",
  "Mhatet el Raml",
  "Smouha",
  "Ziznia",
  "Cleopatra",
  "Ibrahamiya",
  "Victoria",
  "El Ekbal",
  "Lauran",
  "Camp Shezar",
  "Al-Shattaby",
  "Sidi Gaber",
  "Azarita",
  "Anfushi",
  "Al Saraya",
  "Bab Sharq",
  "El Atareen",
  "Al-Qabbari",
  "Al Hadara",
  "Dekheila",
  "El Laban",
  "Bacchus",
  "Bahary",
  "Bulkley",
  "Tharwat",
  "Roshdy",
  "Sporting",
  "Sidi Bishr Bahri",
  "Sidi Bishr Tram",
  "Shods",
  "Safar",
  "Fleming",
  "Muharram Beh",
  "Kafr Abdo",
  "Wabor El Maya",
  "Karmoz",
  "Stanley",
  "Saba Basha",
  "Janaklis",
  "Ras El ten",
  "Gleem",
  "Hy El Gomrok",
  "Al-Werdian",
  "Maamoura",
  "Al Montazah",
  "Al Max",
  "Burj Al Arab",
  "Amriya",
  "El Sa3a",
  "Gabria"
];
final List<String> alexandriaRegionsForAdd = [
  "Miami",
  "Mandara",
  "Asafra",
  "El Syouf Shma3a",
  "Tram Syouf",
  "El Awayed",
  "Al-Mansheya",
  "Mhatet el Raml",
  "Smouha",
  "Ziznia",
  "Cleopatra",
  "Ibrahamiya",
  "Victoria",
  "El Ekbal",
  "Lauran",
  "Camp Shezar",
  "Al-Shattaby",
  "Sidi Gaber",
  "Azarita",
  "Anfushi",
  "Al Saraya",
  "Bab Sharq",
  "El Atareen",
  "Al-Qabbari",
  "Al Hadara",
  "Dekheila",
  "El Laban",
  "Bacchus",
  "Bahary",
  "Bulkley",
  "Tharwat",
  "Roshdy",
  "Sporting",
  "Sidi Bishr Bahri",
  "Sidi Bishr Tram",
  "Shods",
  "Safar",
  "Fleming",
  "Muharram Beh",
  "Kafr Abdo",
  "Wabor El Maya",
  "Karmoz",
  "Stanley",
  "Saba Basha",
  "Janaklis",
  "Ras El ten",
  "Gleem",
  "Hy El Gomrok",
  "Al-Werdian",
  "Maamoura",
  "Al Montazah",
  "Al Max",
  "Burj Al Arab",
  "Amriya",
  "El Sa3a",
  "Gabria"
];
